[general]
import = ["./themes/github_dark.toml"]

[window]
opacity = 1.0
padding.x = 6
padding.y = 6
decorations = "None"
title = "Alacritty"

[font]
normal.family = "Cascadia Mono"
size = 17

[cursor]
style = { shape = "Block", blinking = "Off" }

[terminal]
shell = { program = "/usr/bin/fish", args = ["-l"] }

[mouse]
hide_when_typing = true
