input {
    kb_layout = hu
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.3 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = pixart-dell-ms116-usb-optical-mouse
    sensitivity = -0.65
}
