windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = term-w1

    match:class = com.mitchellh.ghostty

    workspace = 1
}

windowrule {
    name = firefox-w2

    match:class = firefox

    workspace = 2
}

windowrule {
    name = zed-w3

    match:class = dev.zed.Zed

    workspace = 3
}

windowrule {
    name = helium-w4

    match:class = helium

    workspace = 4
}

windowrule {
    name = fm-w5

    match:class = nemo

    workspace = 5
}

windowrule {
    name = tidal-w9

    match:class = tidal-hifi

    workspace = 9
}

windowrule {
    name = localsend-w8

    match:class = localsend

    workspace = 8
}
