wallpaper {
    monitor =
    # path = ~/Pictures/Wallpapers/minimal-wallpaper.jpg
    # path = ~/Pictures/Wallpapers/river.jpg
    # path = ~/Pictures/Wallpapers/raspycupcake.jpg
    # path = ~/Pictures/Wallpapers/cyberpunk.jpg
    # path = ~/Pictures/Wallpapers/wallhaven-zm7pvo.jpg
    path = ~/Pictures/Wallpapers/wallhaven-rdoey1.png
    # path = ~/Pictures/Wallpapers/wallhaven-9oo8k1.jpg
}

# splash = false
