wallpaper {
    monitor =
    # path = ~/Pictures/Wallpapers/mountains.png
    # path = ~/Pictures/Wallpapers/anime-cyberpunk.png
    # path = ~/Pictures/Wallpapers/anime-bedroom.jpg
    path = ~/Pictures/Wallpapers/japan-artistic.jpg
    # path = ~/Pictures/Wallpapers/hatsune-miku.jpg
    # path = ~/Pictures/Wallpapers/
}

splash = false
