background = 0xFF232634
base = 0xFF303446
alternate_base = 0xFF414559

text = 0xFFC6D0F5
bright_text = 0xFFBABBf1

accent = 0xFF8CAAEE
accent_secondary = 0xFF85C1DC

h1_size = 30
h2_size = 22
h3_size = 16
font_size = 15
small_font_size = 13

icon_theme = "Papirus-Dark"
font_family = "SF Pro Display"
font_family_monospace = "Cascadia Mono"

rounding_large = 16
rounding_small = 12
