$blue = rgb(8caaee)
$blueAlpha = 8caaee
$base = rgb(303446)
$surface0 = rgb(414559)
$text = rgb(c6d0f5)
$textAlpha = c6d0f5
$red = rgb(e78284)
$yellow = rgb(e5c890)
$accent = $blue
$accentAlpha = $blueAlpha
$font = JetBrainsMono Nerd Font

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.config/hypr/walls/japan-bridge.JPG
  blur_passes = 3
  color = $base
}

# LAYOUT
label {
  monitor =
  text = Layout: $LAYOUT
  color = $text
  font_size = 14
  font_family = $font
  position = 0, -40%
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  text = $TIME
  color = $text
  font_size = 120
  font_family = $font
  position = 0, 10%
  halign = center
  valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 30
  font_family = $font
  position = 0, 0%
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor =
  size = 320, 50
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha">󰌾 Logged in as <span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -6%
  halign = center
  valign = center
}
