wallpaper {
    monitor =
    # path = ~/Pictures/Wallpapers/raspycupcake.jpg
    path = ~/Pictures/Wallpapers/wallhaven-rdoey1.png
    # path = ~/Pictures/Wallpapers/wallhaven-qr3mk7.png
    # path = ~/Pictures/Wallpapers/wallhaven-w56v1x.jpg
    # path = ~/Pictures/Wallpapers/wallhaven-9o276d.png
}

splash = false
