source = ./themes/frappe.conf
source = ./cfg/monitor.conf
source = ./cfg/programs.conf
source = ./cfg/autostart.conf
source = ./cfg/env.conf
source = ./cfg/permissions.conf
source = ./cfg/lookandfeel.conf
source = ./cfg/input.conf
source = ./cfg/binds.conf
source = ./cfg/windowworkspace.conf
